import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Deploying NARAPositionArtV1...");
  const Art = await ethers.getContractFactory("NARAPositionArtV1");
  const art = await Art.deploy();
  await art.waitForDeployment();
  const artAddress = await art.getAddress();
  console.log(`NARAPositionArtV1 deployed to: ${artAddress}`);

  const cases = [
    { tier: 0, name: "Tier 0 - New (fresh, quiet)", genesis: false, eternal: false, tokenId: 1, positionId: 1, module: 0 },
    { tier: 1, name: "Tier 1 - Activated (>0)", genesis: false, eternal: false, tokenId: 2, positionId: 2, module: 1 },
    { tier: 2, name: "Tier 2 - Rewarded (>=0.1 ETH)", genesis: false, eternal: false, tokenId: 3, positionId: 3, module: 2 },
    { tier: 3, name: "Tier 3 - One ETH Mark (>=1 ETH)", genesis: false, eternal: false, tokenId: 4, positionId: 4, module: 3 },
    { tier: 4, name: "Tier 4 - Apex (>=10 ETH, amber)", genesis: false, eternal: false, tokenId: 5, positionId: 5, module: 4 },
    { tier: 0, name: "Eternal Ledger (unlocked via burn only)", genesis: true, eternal: true, tokenId: 6, positionId: 6, module: 0 },
    { tier: 0, name: "Genesis Archive", genesis: true, eternal: false, tokenId: 7, positionId: 7, module: 0 },
  ];

  let cardHtml = "";
  for (const c of cases) {
    const seed = ethers.keccak256(ethers.solidityPacked(["uint256"], [c.tokenId]));
    const seedBig = BigInt(seed);
    const svg = await art.svg(c.tier, seedBig, c.module, c.genesis, c.eternal, c.tokenId, c.positionId);
    cardHtml += `
      <div class="card-container">
        <div class="card-title">${c.name}</div>
        <div class="card-svg">${svg}</div>
      </div>
    `;
  }

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>NARA / PROOF OF POSITION</title>
  <style>
    body {
      background-color: #07090A;
      color: #D8D1BD;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 40px;
    }
    h1 {
      font-size: 28px;
      letter-spacing: 4px;
      margin-bottom: 10px;
      color: #D8D1BD;
    }
    .subtitle {
      color: #6F6B63;
      margin-bottom: 40px;
      font-family: monospace;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
      gap: 40px;
    }
    .card-container {
      background-color: #111417;
      border: 1px solid #26241F;
      border-radius: 12px;
      padding: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .card-title {
      font-size: 16px;
      margin-bottom: 15px;
      color: #A88745;
      letter-spacing: 2px;
      font-family: monospace;
    }
    .card-svg {
      width: 100%;
      max-width: 360px;
      aspect-ratio: 1/1;
    }
  </style>
</head>
<body>
  <h1>NARA / PROOF OF POSITION</h1>
  <div class="subtitle">Fully on-chain instruments. Generated by NARAPositionArtV1.svg(). No image uploaded.</div>
  <div class="grid">
    ${cardHtml}
  </div>
</body>
</html>
  `;

  const outputDir = "C:/Users/linas/.gemini/antigravity/brain/93846786-738d-491f-958d-3c4c7ec425e3/scratch/nft-preview";
  fs.mkdirSync(outputDir, { recursive: true });
  const outputPath = path.join(outputDir, "index.html");
  fs.writeFileSync(outputPath, html);
  console.log(`Preview generated at: ${outputPath}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
